version: "3.9"
services:
  wordpress:
    container_name: ${PROJECT_ID}
    image: wordpress:6.7.2
    volumes:
      - ./src/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    ports:
      - ${PORT}:80
    networks:
      - webnet
    restart: always

networks:
  webnet:
    name: webnet
    external: true
